### ISSUE TITLE
Interpolation app broken

### ISSUE THREAD

**Issue by svgeesus** [LeaVerou/color.js#115] opened 2021-11-29 11:14 UTC
Selecting `srgb-linear` as the interpolation space breaks is with this error

> Oops! 😳 Something went wrong with the expression if(!color1.inGamut(outputSpace), "OOG"): color1.inGamut is not a function
Data was: {"colorStr1":"[url('color1') or 'hsl(90 50% 45%)']","color1":[""],"colorStr2":"[url('color2') or 'hsl(210 80% 55%)']","color2":[""],"showGradient":true,"outputSpace":"[color1.spaceId]","gamutMapping":true,"gradient":[{"space":"lch","numSteps":10,"delta":"","stepCount":[""],"step":[{"color":"","outputColor":[""],"gradientStep":[""]}],"cssGradient":["linear-gradient(to right, ","",")"]}],"colorSpace":[{}]}

**Comment by svgeesus** [comment] 2021-11-29 11:15
Also

> Source map error: Error: request failed with status 404
Resource URL: https://get.mavo.io/stable/mavo.js
Source Map URL: maps/mavo.js.map

**Comment by svgeesus** [comment] 2021-11-29 11:17
However, https://colorjs.io/docs/interpolation.html is **not** broken so this seems specific to that app.

**Comment by LeaVerou** [comment] 2022-06-16 11:10
Cannot reproduce anymore, closing. There are some errors in the console from before Mavo expressions resolve, but don't seem to be affecting functionality.
Note that colors will not show if you select `srgb-linear` as the **output space**, since your browser doesn't support that, but selecting it as the interpolation space should be fine.

**Closed by LeaVerou** 2022-06-16 11:10 UTC
